name: Deploy Jekyll to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Ruby 및 Bundler 설치 (Gemfile이 있을 경우)
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      # 3. Jekyll 의존성 설치 (Gemfile이 있을 경우)
      - name: Install dependencies
        run: bundle install
        working-directory: .

      # 4. Jekyll 빌드
      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site
        working-directory: .

      # 5. gh-pages 브랜치로 배포
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          # (선택) 커밋 작성자 정보
          user_name: github-actions
          user_email: github-actions@github.com
