name: SpringBoot Setup & Build

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 디스크 슬롯 디렉토리 및 권한 설정
      - name: Create directory structure
        run: |
          mkdir -p ~/springboot-slots/slot1/{bin,config,logs,tmp}
          chmod -R 755 ~/springboot-slots
          echo "✅ 디렉토리 생성 및 권한 완료"

      # 3. Maven 3.9.6 설치
      - name: Install Maven 3.9.6
        run: |
          MAVEN_VERSION=3.9.6
          curl -sL https://downloads.apache.org/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.zip -o maven.zip
          unzip -q maven.zip -d ~/springboot-slots/slot1/bin
          echo "MAVEN_HOME=$HOME/springboot-slots/slot1/bin/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "PATH=$HOME/springboot-slots/slot1/bin/apache-maven-${MAVEN_VERSION}/bin:$PATH" >> $GITHUB_ENV
          echo "✅ Maven 설치 완료"

      # 4. pom.xml 없으면 소스 ZIP 다운로드
      - name: Download Spring Boot project if missing
        run: |
          if [ ! -f "./pom.xml" ]; then
            echo "⚠️ pom.xml 없음 → Spring PetClinic 예제 프로젝트 다운로드 중..."
            curl -L -o springboot.zip "https://github.com/spring-projects/spring-petclinic/archive/refs/heads/main.zip"
            unzip -q springboot.zip -d ~/springboot-slots/slot1/tmp
            mv ~/springboot-slots/slot1/tmp/spring-petclinic-main/* ./
            echo "✅ 프로젝트 다운로드 완료"
          else
            echo "✅ 기존 pom.xml 발견"
          fi

      # 5. Maven 버전 확인
      - name: Verify Maven installation
        run: mvn -v

      # 6. Spring Boot 빌드 (Checkstyle 스킵)
      - name: Build Spring Boot project (skip checkstyle)
        run: |
          mvn clean package -DskipTests -Dcheckstyle.skip=true
          cp target/*.jar ~/springboot-slots/slot1/bin/app.jar
          chmod +x ~/springboot-slots/slot1/bin/app.jar
          echo "✅ JAR 빌드 완료 및 저장됨"

      # 7. 설정 파일 복사
      - name: Copy config files
        run: |
          if [ -d "./src/main/resources" ]; then
            cp -r ./src/main/resources/* ~/springboot-slots/slot1/config/
            echo "✅ 설정 파일 복사 완료"
          else
            echo "⚠️ 설정 파일 없음"
          fi

      # 8. 백그라운드로 Spring Boot 실행
      - name: Run Spring Boot JAR
        run: |
          nohup java -jar ~/springboot-slots/slot1/bin/app.jar > ~/springboot-slots/slot1/logs/server.log 2>&1 &
          echo "✅ Spring Boot 서버 실행됨 (logs/server.log 확인 가능)"

      # 9. 전체 디렉토리 구조 출력
      - name: Show slot layout
        run: |
          sudo apt-get install -y tree > /dev/null
          tree ~/springboot-slots/slot1 || find ~/springboot-slots/slot1
